[versions]
slf4j = "2.0.17"
commons-io = "2.21.0"
intellij-annotations = "26.0.2-1"
jackson = "2.20.1"
httpclient = "4.5.14"
jsoup = "1.21.2"
base64 = "2.3.9"
json = "20250517"
ibxm-fork = "a75"
rhino-engine = "1.9.0"
groovy = "5.0.3"
spock-core = "2.4-groovy-5.0"
logback-classic = "1.5.23"
maven-publish-plugin = "0.35.0"
commons-codec = "1.17.1"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
intellij-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "intellij-annotations" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
httpclient = { group = "org.apache.httpcomponents", name = "httpclient", version.ref = "httpclient" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
base64 = { group = "net.iharder", name = "base64", version.ref = "base64" }
json = { group = "org.json", name = "json", version.ref = "json" }
ibxm-fork = { group = "com.github.walkyst", name = "ibxm-fork", version.ref = "ibxm-fork" }
rhino-engine = { group = "org.mozilla", name = "rhino-engine", version.ref = "rhino-engine" }
groovy = { group = "org.apache.groovy", name = "groovy", version.ref = "groovy" }
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock-core" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.14.1" }

[plugins]
maven-publish-base = { id = "com.vanniktech.maven.publish.base", version.ref = "maven-publish-plugin" }
